services:
  - type: web
    name: swift_Delivery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runserver 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Swift_Delivery.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-dev-secret-key
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    plan: free
    autoDeploy: true

      
