# Generated by Django 5.1.1 on 2024-11-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0002_cafeteria_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cafeteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='swift_delivery_backend.cafeteria'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
