# Generated by Django 5.1.1 on 2024-12-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0003_menuitem_cafeteria_menuitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cafeteria',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cafeterias',
            field=models.ManyToManyField(related_name='menu_items', to='swift_delivery_backend.cafeteria'),
        ),
    ]
