# Generated by Django 5.1.1 on 2024-12-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cafeterias',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cafeteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='swift_delivery_backend.cafeteria'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swift_delivery_backend.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
