# Generated by Django 5.1.1 on 2024-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0006_remove_menuitem_cafeterias_menuitem_cafeteria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='cafeteria',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cafeteria',
            field=models.ManyToManyField(blank=True, null=True, related_name='menu_items', to='swift_delivery_backend.cafeteria'),
        ),
    ]
