# Generated by Django 5.2.15 on 2026-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0008_remove_order_menu_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteria',
            name='vendor_type',
            field=models.CharField(choices=[('cafeteria', 'Cafeteria'), ('grills', 'Grills'), ('pastries', 'Pastries'), ('drinks', 'Drinks')], default='cafeteria', max_length=20),
        ),
    ]
