# Generated by Django 5.2.15 on 2026-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0013_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
