# Generated by Django 5.2.15 on 2026-06-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0015_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='swift_delivery_backend.customer'),
        ),
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vendors', to='swift_delivery_backend.customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='swift_delivery_backend.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'vendor')},
            },
        ),
    ]
