# Generated by Django 5.2.15 on 2026-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0018_order_delivery_latitude_order_delivery_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='campus_location',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='provider_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='CampusLocation',
        ),
    ]
