# Generated by Django 5.2.15 on 2026-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0020_normalize_customer_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
