# Generated by Django 5.2.15 on 2026-07-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0021_cart_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCartNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cart_notes', to='swift_delivery_backend.customer')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
