# Generated by Django 5.2.15 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift_delivery_backend', '0024_vendor_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='notes',
            new_name='vendor_notes',
        ),
        migrations.AlterField(
            model_name='cart',
            name='vendor_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='savedcartnote',
            name='note_type',
            field=models.CharField(
                choices=[('vendor', 'Vendor'), ('delivery', 'Delivery')],
                default='vendor',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
