services:
  - type: web
    name: Swift_Delivery
    env: python
    buildCommand: "pip install -r Swift_Delivery/requirements.txt"
    startCommand: "cd Swift_Delivery && gunicorn Swift_Delivery.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Swift_Delivery.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-dev-secret-key
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
    plan: free
    autoDeploy: true

      
